export const CountryList = {
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei Darussalam",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GH: "Ghana",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Lao People's Democratic Republic",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PR: "Puerto Rico",
  PS: "Palestine, State of",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russian Federation",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SI: "Slovenia",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  US: "United States of America",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia"
} as const

export type CountryCode = keyof typeof CountryList
export type ColorMapping = {
  [K in CountryCode]: number
}

export const ColorList: ColorMapping = {
  AE: 1,
  AF: 0,
  AG: 0,
  AI: 0,
  AL: 0,
  AM: 3,
  AO: 0,
  AQ: 4,
  AR: 1,
  AS: 0,
  AT: 0,
  AU: 0,
  AW: 0,
  AZ: 2,
  BA: 0,
  BB: 0,
  BD: 0,
  BE: 1,
  BF: 4,
  BG: 0,
  BH: 0,
  BI: 0,
  BJ: 0,
  BL: 0,
  BM: 0,
  BN: 0,
  BO: 2,
  BQ: 0,
  BR: 3,
  BS: 0,
  BT: 0,
  BW: 0,
  BY: 1,
  BZ: 2,
  CA: 1,
  CD: 2,
  CF: 0,
  CG: 0,
  CH: 1,
  CI: 2,
  CL: 3,
  CM: 2,
  CN: 0,
  CO: 2,
  CR: 0,
  CU: 0,
  CV: 0,
  CW: 0,
  CY: 0,
  CZ: 0,
  DE: 2,
  DJ: 1,
  DK: 0,
  DM: 0,
  DO: 0,
  DZ: 0,
  EC: 1,
  EE: 0,
  EG: 1,
  EH: 2,
  ER: 0,
  ES: 0,
  ET: 3,
  FI: 2,
  FJ: 0,
  FK: 0,
  FM: 0,
  FO: 0,
  FR: 4,
  GA: 1,
  GB: 1,
  GD: 0,
  GE: 0,
  GF: 0,
  GH: 0,
  GL: 0,
  GM: 0,
  GN: 1,
  GP: 0,
  GQ: 0,
  GR: 1,
  GT: 1,
  GU: 0,
  GW: 0,
  GY: 0,
  HN: 0,
  HR: 2,
  HT: 1,
  HU: 4,
  ID: 1,
  IE: 0,
  IL: 0,
  IN: 2,
  IQ: 4,
  IR: 1,
  IS: 0,
  IT: 2,
  JM: 0,
  JO: 2,
  JP: 0,
  KE: 0,
  KG: 0,
  KH: 0,
  KM: 0,
  KN: 0,
  KP: 1,
  KR: 0,
  KW: 0,
  KY: 0,
  KZ: 3,
  LA: 0,
  LB: 2,
  LC: 0,
  LK: 0,
  LR: 3,
  LS: 0,
  LT: 0,
  LU: 0,
  LV: 2,
  LY: 3,
  MA: 1,
  MD: 0,
  ME: 1,
  MF: 0,
  MG: 0,
  MH: 0,
  MK: 4,
  ML: 3,
  MM: 1,
  MN: 0,
  MP: 0,
  MQ: 0,
  MR: 1,
  MS: 0,
  MT: 0,
  MU: 0,
  MV: 0,
  MW: 0,
  MX: 0,
  MY: 0,
  MZ: 2,
  NA: 2,
  NC: 0,
  NE: 2,
  NG: 1,
  NI: 1,
  NL: 0,
  NO: 0,
  NP: 0,
  NR: 0,
  NZ: 0,
  OM: 0,
  PA: 1,
  PE: 0,
  PF: 0,
  PG: 0,
  PH: 0,
  PK: 3,
  PL: 3,
  PR: 0,
  PS: 0,
  PT: 1,
  PW: 0,
  PY: 0,
  QA: 0,
  RE: 0,
  RO: 1,
  RS: 3,
  RU: 4,
  RW: 1,
  SA: 3,
  SB: 0,
  SC: 0,
  SD: 2,
  SE: 1,
  SI: 1,
  SK: 1,
  SL: 0,
  SN: 2,
  SO: 2,
  SR: 1,
  SS: 1,
  ST: 0,
  SV: 2,
  SX: 0,
  SY: 1,
  SZ: 0,
  TC: 0,
  TD: 4,
  TG: 1,
  TH: 2,
  TJ: 2,
  TL: 0,
  TM: 2,
  TN: 1,
  TO: 0,
  TR: 0,
  TT: 0,
  TV: 0,
  TW: 0,
  TZ: 3,
  UA: 2,
  UG: 4,
  US: 0,
  UY: 0,
  UZ: 1,
  VC: 0,
  VE: 1,
  VG: 0,
  VI: 0,
  VN: 1,
  VU: 0,
  WS: 0,
  XK: 2,
  YE: 1,
  YT: 0,
  ZA: 1,
  ZM: 1
} as const

export type Tab = "Chart"
export type PopulationData = {
  [countryCode in CountryCode]: number[][][]
}
